version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: e-learn
      POSTGRES_USER: elearn
      POSTGRES_PASSWORD: nraele
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - django_network

  django:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: e-learn
      DB_USER: elearn
      DB_PASSWORD: nraele
      DB_HOST: db
      DB_PORT: 5432
    networks:
      - django_network

volumes:
  db_data:

networks:
  django_network:
    driver: bridge